### ISSUE TITLE
Retry error when optimizing using IonQ QC

### ISSUE THREAD

**Issue by Thevendran** [qiskit-community/qiskit-braket-provider#125]
Hi. I am getting retry error when performing optimization using IonQ instances. Please refer to the following optimization code snippet.

`sampler = BackendSampler(
    backend=AWSBraketProvider().get_backend("Harmony"),
    skip_transpilation=False,
    options={"shots": 100}
)
qaoa = QAOA(sampler=sampler, optimizer=COBYLA())
qaoa_solver = MinimumEigenOptimizer(qaoa)
result = qaoa_solver.solve(quadratic_function)`

Attached is the error message that I am getting.
![image](https://github.com/qiskit-community/qiskit-braket-provider/assets/87386865/dbee2a91-8bdc-444b-a9b1-ff611f891672)

I am sure this is caused by the job wait time. I notice the job remains queued in Amazon Braket. However, I am unable to find an option/parameter to extend the wait time. Please assist.

Thanks.

**Comment by virajvchaudhari** [comment]
Hello @Thevendran, I was able to reproduce this issue on our end. We'll be taking a look at this and will reach out with further information/questions. Thanks for flagging this!

**Comment by speller26** [comment]
From what I can tell, you can adjust the `retry` wait time by setting the [`QISKIT_BRAKET_PROVIDER_MAX_DELAY`](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/qiskit_braket_provider/providers/braket_job.py#L24) environment variable, which defaults to 6s (which is definitely too short for a QPU).

However, `retry` probably isn't needed at all; the Amazon Braket SDK already allows you to adjust the max wait time and polling interval. It's probably worth rewriting braket_job.py to go this route instead.
