### ISSUE TITLE
 QuEra Aquila unavailable in backends

### ISSUE THREAD

**Issue by Thevendran** [qiskit-community/qiskit-braket-provider#126]
### Steps to reproduce the problem
Run AWSBraketProvider().backends("Aquila") and observe returned empty backend.

### What is the current behavior?
AWSBraketProvider().backends("Aquila") returns no backend.

### What is the expected behavior?
Should return "QuEra Aquila" backend.

**Comment by virajvchaudhari** [comment]
Hello @Thevendran, Thanks for reaching out! Qiskit Provider [doesn't support](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/qiskit_braket_provider/providers/braket_provider.py#L19-L28) non-gate based devices that can run Analog Hamiltonian Simulation (AHS) quantum tasks. For submitting Analog Hamiltonian Simulation (AHS) quantum tasks, you can directly use [AWS Braket](https://docs.aws.amazon.com/braket/latest/developerguide/braket-quera-submitting-analog-program-aquila.html). Let us know if you need any additional information or assistance.

**Comment by kshitijc** [comment]
Please reopen if you have any more questions. Thanks!
