### ISSUE TITLE
Braket Provider returns measurement counts on all qubits instead of measured qubits

### ISSUE THREAD

**Issue by licedric** [qiskit-community/qiskit-braket-provider#130]
The Qiskit-Braket provider returns measurement counts on all qubits, not just measured ones. This behavior is different from other Qiskit providers.

### Steps to reproduce the problem

```
sim = BraketLocalBackend()
qc = QuantumCircuit(2, 1)
qc.h(0)
qc.h(1)
qc.measure(0, 0)
task = execute(qc, sim)
result = task.result()
counts = result.get_counts()
print(counts)
```

### What is the current behavior?

Measurement results on all qubits, even those not explicitly measured are returned:
`{'11': 273, '00': 251, '10': 264, '01': 236}`

### What is the expected behavior?

Only results from the measured qubit are returned. This would match the behavior of other Qiskit backends.

**Comment by licedric** [comment]
Counts are read in [this line](https://github.com/qiskit-community/qiskit-braket-provider/blob/ec7d04718550c7454c06922859ba0d6a62e4cd7b/qiskit_braket_provider/providers/braket_job.py#L51). Since Braket always measures all bits under the hood, this line will pull measurement counts on all qubits.

**Comment by kshitijc** [comment]
The provider implements handling for measure [here](https://github.com/qiskit-community/qiskit-braket-provider/blob/ec7d04718550c7454c06922859ba0d6a62e4cd7b/qiskit_braket_provider/providers/adapter.py#L429), but it needs to access the sample result type [here](https://github.com/qiskit-community/qiskit-braket-provider/blob/ec7d04718550c7454c06922859ba0d6a62e4cd7b/qiskit_braket_provider/providers/braket_job.py#L51).

**Comment by mdpratt** [comment]
Do we want to consider making an equivalent to qiskit's  `qc.measure_all()`?

**Comment by ashlhans** [comment]
A fix for this issue is in progress [here](https://github.com/qiskit-community/qiskit-braket-provider/pull/169). This uses Braket's `measure` instruction and will measure the subset of qubits on any device that supports partial measurement.

**Comment by speller26** [comment]
Completed in #169
