### ISSUE TITLE
Run OpenQASM3 on devices that supports it

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/qiskit-braket-provider#14]
### What is the expected enhancement?
Some of Braket devices support OpenQASM3 execution.
We can skip circuit-to-citcuit conversion and execute `circuit.to_qasm()` directly against Braket devices.

**Comment by Morcu** [comment]
This may help https://docs.aws.amazon.com/braket/latest/developerguide/braket-openqasm.html

**Comment by robotAstray** [comment]
Hi @IceKhan13, would you like us to use `circuit.to_qasm()` in the tutorials? or somewhere in the codebase directly?

**Comment by robotAstray** [comment]
@IceKhan13 just so I understand, not all Braket Devices support OpenQASM3 therefore we should check if the device supports it. if it does then we apply `circuit.to_qasm` after skipping circuit-to-circuit conversion.

**Comment by robotAstray** [comment]
This page confirms `to_qasm` returns a QASMType which is teh string representation of a circuit 
https://docs.qbraid.com/en/latest/_modules/qbraid/transpiler/cirq_qasm/qasm_conversions.html#to_qasm

**Comment by robotAstray** [comment]
Hello @IceKhan13 @Morcu, 

 I've been considering the enhancement we discussed regarding OpenQASM3 support on Braket devices, and I'd like to share an alternative approach.
 What about making adjustment to  `braket_backend.py` file in the `AWSBraketBackend` class?

I was thinking of adding the OpenQASM3 support check directly within the `run()` method of the `AWSBraketBackend` class in the `braket_backend.py` file. Specifically, we could include the following logic:

```python
is_openqasm3_supported = "braket.ir.openqasm.program" in self._device.properties.action
```
This would allow us to check if the Braket device supports OpenQASM3 execution directly within the backend. If the check is successful, we can then execute the OpenQASM3 code generated from the Qiskit circuit using the `circuit.to_qasm()` method.

I just wanted to gather your thoughts on it. Please let me know if I've misunderstood any of your requirements. I'm open to your feedback. Thank you.

**Comment by IceKhan13** [comment]
@robotAstray I like that approach! we can check if backend support openqasm and run depending on that.
We can also add argument like `run_openqasm_if_possible: bool = True`, which will be `True` by default, which mean if backend supports openqasm run it like that. But if user sets `run_openqasm_if_possible` to `False` it will be running through gate converter always.

**Comment by robotAstray** [comment]
@IceKhan13 makes sense! I will work on this and open a draft PR when ready!

**Comment by robotAstray** [comment]
Hello @IceKhan13,

I've written some code and conducted tests, but I encountered issues when attempting to skip the circuit-to-circuit conversion in favor of using OpenQasm3. After discussing this on Slack, it appears that we won't be able to implement this without going through the circuit-to-circuit conversion process.
You can find the conversation detailing of the conversation  [here](https://qiskit.slack.com/archives/C04KY9T71AA/p1692749913148119)

To implement this, I still need to convert the `QuantumCircuit` to a `Braket Circuit` object and then use that to generate the `braket.ir.openqasm.Program object.`"
