### ISSUE TITLE
Upgrade requirements to allow qiskit~=1.0.0

### ISSUE THREAD

**Issue by ryanhill1** [qiskit-community/qiskit-braket-provider#161]
### What is the expected enhancement?

Currently have upper-bound on qiskit version. Would like make necessary updates to allow working with latest qiskit version.

https://github.com/qiskit-community/qiskit-braket-provider/blob/bc9e399cf0f5cc3e7cbccba4c6d69504ef59d2ec/requirements.txt#L2

**Comment by virajvchaudhari** [comment]
Thank you for this issue! We will look into this.
