### ISSUE TITLE
Improve unit test coverage to 100%

### ISSUE THREAD

**Issue by yitchen-tim** [qiskit-community/qiskit-braket-provider#177]
Currently, the coverage of unit test is about 89%.

### What is the expected enhancement?
The test coverage is 100%.

### Acceptance criteria
- The test coverage is 100%.
- CI does not accept PRs where coverage is less than 100%

**Comment by WingCode** [comment]
@yitchen-tim  / @rmshaffer  I will like to take up this issue. Could you assign it to me please?

**Comment by yitchen-tim** [comment]
Hi @WingCode , per UnitaryHack guideline, an issue is assigned only at the time it's merged or closed. If you start contributing to an issue, you can comment on this issue so that other UnitaryHack attendees know.

**Comment by WingCode** [comment]
Okay. I have started to contribute towards this issue

**Comment by yitchen-tim** [comment]
Thank you @WingCode for the contribution!
