### ISSUE TITLE
Tests: mock tests for cloud devices

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/qiskit-braket-provider#19]
### What is the expected enhancement?

Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-braket-provider?pullRequest=48) before we can accept your contribution.

Implement mock tests for Braket provider, backend and job for cloud devices.

As a referece for mock end points see https://github.com/aws/amazon-braket-sdk-python/pull/532

**Comment by IceKhan13** [comment]
@Morcu wanna jump on it after HybridJobs containers?

**Comment by WingCode** [comment]
@IceKhan13 I would like to take a stab at this issue. Could you assign it to me?

**Comment by IceKhan13** [comment]
@WingCode done! Thank you again :)

**Comment by JordanAWS** [comment]
@WingCode Any updates on your progress? Do you need any support?

**Comment by WingCode** [comment]
@JordanAWS Thank you for reaching out. I need some support over in #107. I will mention you over there since it is related to that PR.

**Comment by JordanAWS** [comment]
@WingCode Thanks for your work so far on this PR. You will have until June 20th to complete all requested changes and get the code approved and merged! Please don't hesitate to reach out if you need support.
