### ISSUE TITLE
Prebuilt docker container with examples

### ISSUE THREAD

**Issue by IceKhan13** [qiskit-community/qiskit-braket-provider#35]
### What is the expected enhancement?

Step 1: Update https://github.com/aws/amazon-braket-containers/pull/34 to match the versions used in the [base container](https://github.com/aws/amazon-braket-containers/tree/main/base).

Step 2: Open a PR in https://github.com/aws/amazon-braket-examples/tree/main/examples/hybrid_jobs demonstrating use of the Qiskit container.

**Comment by mariapaula14** [comment]
Hi
I already updated the versions between https://github.com/aws/amazon-braket-containers/pull/34 and [base container](https://github.com/aws/amazon-braket-containers/tree/main/base).

Pull request: https://github.com/IceKhan13/amazon-braket-containers/pull/1

Could you confirm me what is the second step?

**Comment by IceKhan13** [comment]
Hey @mariapaula14 !

Thank you for doing this!

Second step will be a separate PR to braket examples repo which will be showing how to use qiskit-braket container in a similar fashion like https://github.com/aws/amazon-braket-examples/blob/main/examples/hybrid_jobs/3_Bring_your_own_container/bring_your_own_container.ipynb, you can use https://qiskit-community.github.io/qiskit-braket-provider/tutorials/2_tutorial_hybrid_jobs_byoc.html as guidance well

**Comment by JordanAWS** [comment]
@mariapaula14 Please don't hesitate to reach out if you have any questions!

**Comment by JordanAWS** [comment]
@mariapaula14 Do you think you'll be able to finish this issue before the end of the hackathon today?

**Comment by JordanAWS** [comment]
@mariapaula14 Thanks for your work so far on this issue! The hackathon has now ended, but if you're still interested in working on this project, we can offer AWS credits for completion :)

**Comment by JordanAWS** [comment]
@mariapaula14 Since you did open the PR with the main functionality, you will still have until June 20th to complete the notebooks for the bounty. Please let us know if you need any support!

**Comment by christianbmadsen** [comment]
We now have Qiskit in the supported Braket Hybrid Jobs base container (https://github.com/amazon-braket/amazon-braket-containers/pull/107) and are updating the example in this repository to use that container which is simpler https://github.com/qiskit-community/qiskit-braket-provider/pull/127
