### ISSUE TITLE
No region error when trying to reproduce 0_tutorial_qiskit-braket-provider_overview.ipynb

### ISSUE THREAD

**Issue by kalpakghosh** [qiskit-community/qiskit-braket-provider#44]
### Steps to reproduce the problem
I tried reproducing the results given in the 0_tutorial_qiskit-braket-provider_overview.ipynb

### What is the current behavior?
Whenever I try to call the devices in Braket there is a no region error. See attached screenshot.
### What is the expected [behavior?]
How to overcome thus error. Help would be appreciated.
![Screenshot from 2022-06-14 16-09-20](https://user-images.githubusercontent.com/83826611/173559194-b002a6be-4f64-461a-8283-f2b5756e7497.png)

**Comment by IceKhan13** [comment]
Hello @kalpakghosh! Thank you for raising this issue

I think you forgot to authenticate yourself in AWS. One way to do that is set env variables.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set

so, it would be something like that:
```python
import os 

os.environ["AWS_ACCESS_KEY_ID"] = "<YOUR_ACCESS_KEY>"
os.environ["AWS_SECRET_ACCESS_KEY"] = "<YOUR_SECRET_ACCESS_KEY>"
os.environ["AWS_DEFAULT_REGION"] = "<YOUR_REGION>"
```

Fill all variables and run it as first paragraph.

I think it is a useful find and if you want you can contribute by adding this explanation to [quickstart guide](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/docs/quickstart_guide.md) for example

**Comment by kalpakghosh** [comment]
Thank you very much @IceKhan13 for your help. I am now able to call the Braket devices and I'll try to add this explanation to the quickstart guide.
