### ISSUE TITLE
Rename AWSBraketJob to AmazonBraketTask

### ISSUE THREAD

**Issue by JordanAWS** [qiskit-community/qiskit-braket-provider#45]
https://github.com/qiskit-community/qiskit-braket-provider/blob/1f64aaeceb241df3eb10e696f1e5034e73c1d712/qiskit_braket_provider/providers/braket_job.py#L63

**Make sure that `AWSBraketJob` remains an alias for `AmazonBraketTask`** to avoid breaking existing code.

**Comment by JordanAWS** [comment]
Will also need to edit all other references to `AWSBraketJob` in the rest of this repo. I'd recommend searching "AWSBraketJob" in your local IDE to find all references, since the search feature on GitHub often misses some.

**Comment by IceKhan13** [comment]
@dexter2206 I like second option more 😄  if you do not mind doing this, it would be great!

I will assign it to you for now then. Thank you ❤️

**Comment by devilkiller-ag** [comment]
Hi, Can I work on this issue?

**Comment by devilkiller-ag** [comment]
Do I need to re run notebooks in doc to change the AWSBraketJob Name?

**Comment by IceKhan13** [comment]
@devilkiller-ag yes, that would be great :) 
Do not forget about deprecation too

**Comment by prakharb10** [comment]
Yeah, I encountered the same error. There are additional steps for running the code outlined here: https://aws.amazon.com/blogs/quantum-computing/introducing-the-qiskit-provider-for-amazon-braket/

Hence, the need for an AWS account

**Comment by devilkiller-ag** [comment]
@IceKhan13 I have added Deprecation Warnings.

**Comment by devilkiller-ag** [comment]
@IceKhan13 I tried making AWS Account, It's not accepting Indian Back Credit Card. It's particularly asking for MasterCard, Visa or AmEx. Is their any other way to rectify docs?

**Comment by christianbmadsen** [comment]
> Is their any other way to rectify docs?

@devilkiller-ag we are assessing options for you to get unblocked. Will circle back with suggested path. Thanks!

**Comment by christianbmadsen** [comment]
@devilkiller-ag we have identified next steps to get you unblocked. Could you send an email to unitary-hack-braket-support@amazon.com and we will follow-up with you? Thanks!

**Comment by devilkiller-ag** [comment]
@christianbmadsen sure I am sending it

**Comment by devilkiller-ag** [comment]
Hi @christianbmadsen, Thank You for the gift card. When I am putting card details along with my name and home address on the AWS Payment Page. It’s saying ‘The payment method cannot be verified. Check your information and try again.’. In the gift card you sent it’s written it’s valid in the United States only. Is this error due to this? Kindly, help me with this.

**Comment by devilkiller-ag** [comment]
Hi @IceKhan13 , @christianbmadsen Any Updates on this?

**Comment by JordanAWS** [comment]
@devilkiller-ag We're working on find you a solution. In the meantime, is there any chance you are part of a university or institution that could provide an AWS account or credit card?

**Comment by devilkiller-ag** [comment]
I am currently in University, and have University ID. But I am not sure they can provide me with that. But, I am trying to get a MasterCard virtual card from third party net banking platforms in India.

**Comment by JordanAWS** [comment]
@devilkiller-ag We are working on a solution, please stand by.

**Comment by robotAstray** [comment]
Hello, are people allowed to work on this issue? Or since it has been taken we should work on something else?

**Comment by JordanAWS** [comment]
@devilkiller-ag Were you able to get up and running on AWS with advice from our team, or are you still blocked?

**Comment by devilkiller-ag** [comment]
Hi @JordanAWS , I contacted my University,but they informed me that they don't use AWS service. Moreover, I tried to create accounts with banks providing virtual card of MasterCard but failed due to citizenship requirements.

**Comment by robotAstray** [comment]
@JordanAWS  I also would like to set up Aws so that I can complete this issue would you please provide a gift card for me as well?

**Comment by devilkiller-ag** [comment]
@JordanAWS  I successfully got a mastercard and created an AWS account. Thanks for your help I will complete this issue soon.

**Comment by robotAstray** [comment]
@JordanAWS I just noticed that when running the notebook I get this, despite installing the aws cli
![Screenshot from 2023-06-06 05-57-19](https://github.com/qiskit-community/qiskit-braket-provider/assets/62884362/32d0fe62-3b65-4d76-9706-d79b57131e8e)

**Comment by robotAstray** [comment]
I was able to fix everything, and run everything apart for 0_tutorial_qiskit-braket-provider_overview.ipynb, which has the error above

**Comment by devilkiller-ag** [comment]
@IceKhan13, for running the tutorials - [0_tutorial_qiskit-braket-provider_overview.ipynb](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/docs/tutorials/0_tutorial_qiskit-braket-provider_overview.ipynb) and [2_tutorial_hybrid_jobs_byoc.ipynb](https://github.com/qiskit-community/qiskit-braket-provider/blob/main/docs/tutorials/2_tutorial_hybrid_jobs_byoc.ipynb) using AmazonBraketTask that I have renamed, I have to [import qiskit_braket_provider](https://github.com/qiskit-community/qiskit-braket-provider/tree/main/qiskit_braket_provider) from super parent directory I have add `__init__.py` in folder [qiskit-braket-provider](https://github.com/qiskit-community/qiskit-braket-provider/tree/main). Should I do that? Other option is to first commit the changes I have made till yet and then run the folder.

**Comment by robotAstray** [comment]
ok then I will stop working on it! @devilkiller-ag

**Comment by robotAstray** [comment]
Hello, I did not see any submission so far. 

I have checked the UnitaryHack rules and I believe I should be allowed to submit my solution :). 

I hope it is suitable.

 If there are any issues I can make changes.

 Thank you. 
 Best wishes.
@robotAstray

**Comment by JordanAWS** [comment]
Please see the reviews on the individual PRs!
