### ISSUE TITLE
Add separate QUEUED and RUNNING states to task status

### ISSUE THREAD

**Issue by JordanAWS** [qiskit-community/qiskit-braket-provider#46]
https://github.com/qiskit-community/qiskit-braket-provider/blob/1f64aaeceb241df3eb10e696f1e5034e73c1d712/qiskit_braket_provider/providers/braket_job.py#L132

Currently the provider assumes that tasks which have not thrown an error, been canceled, or finished are simply Running. This is not the case. We need a separate check to see if the status is QUEUED. Recommended change:

```
      if "FAILED" in braket_tasks_states:
          status = JobStatus.ERROR
      elif "CANCELLED" in braket_tasks_states:
          status = JobStatus.CANCELLED
      elif all(state == "COMPLETED" for state in braket_tasks_states):
          status = JobStatus.DONE
      elif all(state == "RUNNING" for state in braket_tasks_states):
          status = JobStatus.RUNNING
      else:
          status = JobStatus.QUEUED
```

**Comment by robotAstray** [comment]
do you still need help for this issue?
