### ISSUE TITLE
Transpilation fails for Rigetti devices

### ISSUE THREAD

**Issue by CorentinB78** [qiskit-community/qiskit-braket-provider#50]
I am unable to transpile a simple circuit on any of the two Rigetti devices (Aspen-M-1 and Aspen-11). As a result they cannot be used.
It seems the `coupling_map` attribute of the devices is not populated, so that the transpiler cannot know their topology.

### Steps to reproduce the problem
```Python
from qiskit_braket_provider import AWSBraketProvider
from qiskit import circuit, transpile

device = AWSBraketProvider().get_backend("Aspen-M-1")

circ = circuit.QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.cx(1, 2)

circ_tr = transpile(circ, device)
```

### What is the current behavior?

The following warning:
```
This backend's operations: h,id,p,rx,ry,rz,s,sdg,t,tdg,x,y,z only apply to a subset of qubits. Using this property to get 'basis_gates' for the transpiler may potentially create invalid output
```
and an attribute error is raised. The transpiler complains that the `coupling_map` attribute of the device is `None`.

### What is the expected behavior?

Transpilation should succeed to be able to use the Rigetti devices.

**Comment by kshitijc** [comment]
Closing since the fix has been merged in #108
