### ISSUE TITLE
Memory attribute of a task result is sorted

### ISSUE THREAD

**Issue by CorentinB78** [qiskit-community/qiskit-braket-provider#52]
When a task is run on actual hardware with `memory=True`, the task result object normally contains the list of measurement output for each shot, in the order the shots were realized. With the braket provider however, these are sorted by the value of the output (e.g. all the '000' first, then '100', etc), which makes it no more useful than the number of counts.

The order is correct when using the `BraketLocalBackend`. Also, I was only able to test with retrieved tasks.

### Steps to reproduce the problem
* run a task with more than one shot on device (not simulator), and with `memory=True`
* retrieve the task
* print `task.result().data()['memory']` and notice it is a sorted list

### What is the current behavior?

The task result memory is a sorted list.

### What is the expected behavior?

The task result memory should follow the order the shots were realized

**Comment by IceKhan13** [comment]
@CorentinB78 closing it for now. Let us know if it is need to be reopen or you need any assitance
