### ISSUE TITLE
'wait_until_complete = True' argument in backend.run method is not working.  

### ISSUE THREAD

**Issue by tinyRickk** [qiskit-community/qiskit-braket-provider#54]
### Steps to reproduce the problem

1. Create a random circuit in qiskit and define any available backend from aws-braket provider.
2.  And use the following code
`transpiled_circuit = transpile(circuit,backend = ionq_backend, seed_transpiler = 42) #transpiling according to the choice of backend (ionq)`
`count_list = []`
`for i in range(2): #just to have a longer wait time for demonstration`
`result = ionq_backend.run(transpiled_circuit, shots = 10, wait_until_complete = True)` 
 `#notice that wait_until_complete is true, means it should wait to complete execution`
`count = result.result().get_counts()`
`count_list.append(count)`

### What is the current behavior?
Keeping the wait_until_complete argument to be True doesn't wait for the execution to be completed, it times out if it doesn't get a response fast enough. Currently it throws an error message, 'RetryError: RetryError[Attempts: 27, Value: None]'

### What is the expected behavior?
It is expected that the argument kept True will cause the program to wait until the status of task turns to 'job has been completed successfully'.

### A work around
I have used '`result.wait_for_final_state()`' after `backend.result()` to obtain the same effect.

**Comment by tinyRickk** [comment]
@IceKhan13 I would like to contribute to rectifying this bug. But this would be my first time so I require help with procedure and direction. Thank You.

**Comment by IceKhan13** [comment]
Hey @tinyRickk ! 

Thanks for jumping on it :)  Sure, we will try to help you as much as we can! 

I just checked and we are not supporting `wait_until_complete` argument in `Backend.run` method. As calls are asynchronous we can poll results to check wether job is completed. For that we have `JobResult.wait_for_final_state` method  ([see API doc here](https://qiskit.org/documentation/stubs/qiskit.providers.JobV1.wait_for_final_state.html)) like you mentioned. So, it is not a workaround, it is a correct way to wait for results.

Maybe you looked at AmazonBraket Hybrid Jobs API, which has that argument? 
```python
job = AwsQuantumJob.create(
    device="arn:aws:braket:::device/quantum-simulator/amazon/sv1",
    source_module="data/2_hybrid_jobs/job_script.py",
    entry_point="job_script:main",
    wait_until_complete=False, # <- this one
    job_name="qiskit-braket-vqe",
    image_uri=image_uri,
)
``` 

Can you give me a link where did you get example of using `Backend.run` with `wait_until_complete` argument?

**Comment by tinyRickk** [comment]
Actually I did not find any such example, and I don't exactly remember hoe I got the idea to use this `wait_until_complete` with `Backend.run`. But I guess my conclusion followed that since the `Backend.run` takes in the all the arguments from `Device.run()` in braket so I simply used it.

**Comment by IceKhan13** [comment]
Closing it as we have `JobResult.wait_for_final_state` method  ([see API doc here](https://qiskit.org/documentation/stubs/qiskit.providers.JobV1.wait_for_final_state.html)) for `Job` object
