### ISSUE TITLE
Shor's Algorithm qobj failed to submit

### ISSUE THREAD

**Issue by AFOEK** [qiskit-community/qiskit-braket-provider#57]
### Steps to reproduce the problem
`from qiskit.utils import QuantumInstance
from qiskit.algorithms import Shor
from qiskit_braket_provider import AWSBraketProvider

provider = AWSBraketProvider()
dvc_sim = provider.get_backend("SV1")
N=15
q_i=QuantumInstance(backend=dvc_sim,shots=1024)
shor=Shor(quantum_instance=q_i)
rslt=shor.factor(N)
hsl=rslt.factor[0]
print("Factor result: "+str(hsl))
print(rslt)`
### What is the current behavior?
From the code above I try to factorize N, it get error in line 10 (`rslt=shor.factor(N)`) with error QiskitError: 'Max retry limit reached. Failed to submit the qobj correctly'
### What is the expected behavior?
It submited the factor to SV1 simulator or another quantum devices

**Comment by yitchen-tim** [comment]
@AFOEK Do you continue to see the error about max retry limit reached?

**Comment by AFOEK** [comment]
> @AFOEK Do you continue to see the error about max retry limit reached? 

I will revisit my project. Thanks for reminding me

**Comment by speller26** [comment]
@AFOEK Just checking in if you're still running into problems

**Comment by AFOEK** [comment]
From qiskit the API was deprecated but when I run default circuit which is classic superposition circuit it works
