### ISSUE TITLE
Measure to target

### ISSUE THREAD

**Issue by stigerasmussen** [qiskit-community/qiskit-braket-provider#69]
### Steps to reproduce the problem
Transpiling a circuit, with measurements, from a target creates an AttributeError: 'NoneType' object has no attribute 'error'

### What is the current behavior?
In adapt.py a measurement is added as an instruction as a Nonetype: 
target.add_instruction(Measure(), {(i,): None for i in range(paradigm.qubitCount)})
However, when a circuit with measurements is transpiled it results in an AttributeError.
This happens because target.py (from Qiskit) tries to call .error on the Nonetype. 

### What is the expected behavior?
Suggested solution: revert back to target.add_instruction(Measure()).
Unless there is a good reason to keep measurements as None?

**Comment by yitchen-tim** [comment]
Hi @stigerasmussen , this should be fixed using latest version of qiskit-braket-provider and qiskit. Below is a working example
```
from qiskit_braket_provider import BraketLocalBackend
from qiskit import transpile
from qiskit import QuantumCircuit

local_simulator = BraketLocalBackend()
qc = QuantumCircuit(2, 1)
qc.h(0)
qc.cnot(0,1)
qc.measure([0], [0])

qc_basis = transpile(qc, local_simulator)
qc_basis.draw(output='mpl')
```

**Comment by kshitijc** [comment]
Closing this issue. Please let us know if you still encounter errors.
