### ISSUE TITLE
Support for Parametric Circuits

### ISSUE THREAD

**Issue by kshitijc** [qiskit-community/qiskit-braket-provider#86]
### What is the expected behavior?

Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-braket-provider?pullRequest=48) before we can accept your contribution.

A parametric Qiskit circuit should be converted to a Braket parametric circuit. 
Currently, trying to convert a Qiskit parametric circuit to a Braket circuit like so:

```
from qiskit_braket_provider.providers.adapter import convert_qiskit_to_braket_circuit
from qiskit.circuit import Parameter

theta = Parameter('θ')
qc = QuantumCircuit(1, 1)
qc.rz(theta, 0)
```

yields the following error:
```
TypeError: ParameterExpression with unbound parameters ({Parameter(θ)}) cannot be cast to a float.
```

**Expected outcome**: This should return a Braket circuit with Rz gate and FreeParameter `θ`

**Comment by urihan** [comment]
Hello, I would like to work on this issue! Thank you

**Comment by king-p3nguin** [comment]
Hi, I am also interested in this issue.

**Comment by natestemen** [comment]
@kshitijc this bounty is showing as completed by @urihan, but it looks like it was completed by @king-p3nguin. Please ensure the hacker who has been responsible to the issue being resolved is assigned to the issue. Thanks!

**Comment by JordanAWS** [comment]
@natestemen Just updated. Could you update the UnitaryHack website to reflect @king-p3nguin as the bounty closer? https://unitaryhack.dev/projects/qiskit-braket-provider/
