### ISSUE TITLE
Enable (some) transpilation with Braket

### ISSUE THREAD

**Issue by christianbmadsen** [qiskit-community/qiskit-braket-provider#91]
### What is the expected enhancement?

Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-braket-provider?pullRequest=48) before we can accept your contribution.

The goal of this task is to make transpilation a useful feature when running on Braket backends (issues have been reported for some devices in https://github.com/qiskit-community/qiskit-braket-provider/issues/50)

### Acceptance criteria

Enable [qiskit circuit transpilation](https://qiskit.org/documentation/apidoc/transpiler.html) for Braket via the qiskit-braket provider. The transpiler is expected to succesfully transpile a circuit for a device to a circuit composed of native gates for that device.

**Comment by alibokhamseen** [comment]
Hi @christianbmadsen, can I work on this problem?

**Comment by christianbmadsen** [comment]
Great @ogunsegun! I have assigned the issue to you. Thanks!

**Comment by ogunsegun** [comment]
Where can I submit my code @jcjaskula-aws

**Comment by ogunsegun** [comment]
thanks @jcjaskula-aws

**Comment by DarthRevan07** [comment]
@christianbmadsen can i have a jibe at this too? this is my first time participating, and am not quite sure how this works.... can one problem be assigned to only one assignee?

**Comment by ogunsegun** [comment]
`# Create the Braket provider using your AWS account credentials`
`provider = BraketProvider(region_name='your_aws_region', aws_access_key_id='your_access_key', aws_secret_access_key='your_secret_key')`

`# Execute or analyze the transpiled circuit as needed`
`# For example, you can execute the transpiled circuit on a simulator`
`job = backend.run(transpiled_circuit)`
`result = job.result()`

Note that you need to replace 'your_aws_region', 'your_access_key', and 'your_secret_key' with your actual AWS region and corresponding access key and secret access key. Also, replace 'your_backend_name' with the name of the specific Braket backend you want to use for transpilation.

**Comment by Gmontes01** [comment]
Hello @christianbmadsen this looks like an interesting problem. Can I be assigned to this?

Also a a clarifying questions
For this task do you want us to make it so that you can run the qiskit transpiler with a Braket backend as the device input and get a circuit which is compatible with the device of the Braket backend?
an example of this would be 
````
from qiskit_braket_provider import AWSBraketProvider
from qiskit import circuit, transpile

device = AWSBraketProvider().get_backend("Aspen-M-1")

circ = circuit.QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.cx(1, 2)

circ_tr = transpile(circ, device)`
from the problem you mentioned above. 

And would I be able to test this sufficiently by making a for-loop that would go through all the potential backend devices and make sure that they transpile a given circuit?

**Comment by kshitijc** [comment]
@Gmontes01 Yes, that is correct

**Comment by kshitijc** [comment]
@Gmontes01  - I can assign you as well, but would want to see where the current assignees @ogunsegun and @DarthRevan07 are at.

@ogunsegun @DarthRevan07: Could you let us know if you're still working on this?

**Comment by WingCode** [comment]
@kshitijc I would like to be assigned as well. I am okay with 🅱️ as mentioned over [here](https://github.com/qiskit-community/qiskit-braket-provider/issues/91#issuecomment-1576815128)

**Comment by JordanAWS** [comment]
@WingCode Thanks for your work so far on this PR. You will have until June 20th to complete all requested changes and get the code approved and merged! Please don't hesitate to reach out if you need support.

**Comment by christianbmadsen** [comment]
The PR has been merged. Thanks so much for this contribution @WingCode! Good work!

**Comment by natestemen** [comment]
@JordanAWS / @christianbmadsen / @jcjaskula-aws: it looks like @WingCode was the only hacker to make a contribution here. Should the other two assignees also split the bounty?

**Comment by NosVladimir** [comment]
Hello, I would like to ask if the functionality described in this issue is implemented or not? I'm trying to transpile circuits into the native gates of Braket backends, but so far have not succeeded in that. Example code:
```py
from qiskit import QuantumCircuit, transpile
from qiskit_braket_provider import AWSBraketProvider

circuit = QuantumCircuit(2)
circuit.x(0)
circuit.y(1)
circuit.rzz(1, 0, 1)
print(transpile(circuit, backend=AWSBraketProvider().get_backend("Lucy")).qasm())
```
Output:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[8];
x q[0];
y q[1];
cx q[0],q[1];
rz(1.0) q[1];
cx q[0],q[1];
```
The circuit is not transpiled into the native gate set of the OQC Lucy device, which include `ecr, i, rz, v, x`. What am I missing here?
